// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Grpc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Grpc.Contract {

  /// <summary>Holder for reflection information generated from Grpc.proto</summary>
  public static partial class GrpcReflection {

    #region Descriptor
    /// <summary>File descriptor for Grpc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GrpcReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpHcnBjLnByb3RvEglHcnBjUHJvdG8iNwoMR3JwY1JlcXVlc3RzEicKB3Jl",
            "cXVlc3QYASADKAsyFi5HcnBjUHJvdG8uR3JwY1JlcXVlc3QiIAoLR3JwY1Jl",
            "cXVlc3QSEQoJY29sbGVjdG9yGAEgASgFIjoKDUdycGNSZXNwb25zZXMSKQoI",
            "cmVzcG9uc2UYASADKAsyFy5HcnBjUHJvdG8uR3JwY1Jlc3BvbnNlIiEKDEdy",
            "cGNSZXNwb25zZRIRCgljb2xsZWN0b3IYASABKAUyjwMKC0dycGNTZXJ2aWNl",
            "Ej4KC0dldEN1c3RvbWVyEhYuR3JwY1Byb3RvLkdycGNSZXF1ZXN0GhcuR3Jw",
            "Y1Byb3RvLkdycGNSZXNwb25zZRJBCgxHZXRDdXN0b21lcnMSFy5HcnBjUHJv",
            "dG8uR3JwY1JlcXVlc3RzGhguR3JwY1Byb3RvLkdycGNSZXNwb25zZXMSWQoi",
            "R2V0Q3VzdG9tZXJXaXRoQmlkaXJlY3Rpb25hbFN0cmVhbRIWLkdycGNQcm90",
            "by5HcnBjUmVxdWVzdBoXLkdycGNQcm90by5HcnBjUmVzcG9uc2UoATABElAK",
            "G0dldEN1c3RvbWVyV2l0aENsaWVudFN0cmVhbRIWLkdycGNQcm90by5HcnBj",
            "UmVxdWVzdBoXLkdycGNQcm90by5HcnBjUmVzcG9uc2UoARJQChtHZXRDdXN0",
            "b21lcldpdGhTZXJ2ZXJTdHJlYW0SFi5HcnBjUHJvdG8uR3JwY1JlcXVlc3Qa",
            "Fy5HcnBjUHJvdG8uR3JwY1Jlc3BvbnNlMAFCEKoCDUdycGMuQ29udHJhY3Ri",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.Contract.GrpcRequests), global::Grpc.Contract.GrpcRequests.Parser, new[]{ "Request" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.Contract.GrpcRequest), global::Grpc.Contract.GrpcRequest.Parser, new[]{ "Collector" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.Contract.GrpcResponses), global::Grpc.Contract.GrpcResponses.Parser, new[]{ "Response" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.Contract.GrpcResponse), global::Grpc.Contract.GrpcResponse.Parser, new[]{ "Collector" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GrpcRequests : pb::IMessage<GrpcRequests> {
    private static readonly pb::MessageParser<GrpcRequests> _parser = new pb::MessageParser<GrpcRequests>(() => new GrpcRequests());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GrpcRequests> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.Contract.GrpcReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcRequests() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcRequests(GrpcRequests other) : this() {
      request_ = other.request_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcRequests Clone() {
      return new GrpcRequests(this);
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Grpc.Contract.GrpcRequest> _repeated_request_codec
        = pb::FieldCodec.ForMessage(10, global::Grpc.Contract.GrpcRequest.Parser);
    private readonly pbc::RepeatedField<global::Grpc.Contract.GrpcRequest> request_ = new pbc::RepeatedField<global::Grpc.Contract.GrpcRequest>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Grpc.Contract.GrpcRequest> Request {
      get { return request_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GrpcRequests);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GrpcRequests other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!request_.Equals(other.request_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= request_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      request_.WriteTo(output, _repeated_request_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += request_.CalculateSize(_repeated_request_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GrpcRequests other) {
      if (other == null) {
        return;
      }
      request_.Add(other.request_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            request_.AddEntriesFrom(input, _repeated_request_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GrpcRequest : pb::IMessage<GrpcRequest> {
    private static readonly pb::MessageParser<GrpcRequest> _parser = new pb::MessageParser<GrpcRequest>(() => new GrpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GrpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.Contract.GrpcReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcRequest(GrpcRequest other) : this() {
      collector_ = other.collector_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcRequest Clone() {
      return new GrpcRequest(this);
    }

    /// <summary>Field number for the "collector" field.</summary>
    public const int CollectorFieldNumber = 1;
    private int collector_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Collector {
      get { return collector_; }
      set {
        collector_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GrpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GrpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Collector != other.Collector) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Collector != 0) hash ^= Collector.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Collector != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Collector);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Collector != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Collector);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GrpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.Collector != 0) {
        Collector = other.Collector;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Collector = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GrpcResponses : pb::IMessage<GrpcResponses> {
    private static readonly pb::MessageParser<GrpcResponses> _parser = new pb::MessageParser<GrpcResponses>(() => new GrpcResponses());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GrpcResponses> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.Contract.GrpcReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcResponses() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcResponses(GrpcResponses other) : this() {
      response_ = other.response_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcResponses Clone() {
      return new GrpcResponses(this);
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Grpc.Contract.GrpcResponse> _repeated_response_codec
        = pb::FieldCodec.ForMessage(10, global::Grpc.Contract.GrpcResponse.Parser);
    private readonly pbc::RepeatedField<global::Grpc.Contract.GrpcResponse> response_ = new pbc::RepeatedField<global::Grpc.Contract.GrpcResponse>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Grpc.Contract.GrpcResponse> Response {
      get { return response_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GrpcResponses);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GrpcResponses other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!response_.Equals(other.response_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= response_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      response_.WriteTo(output, _repeated_response_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += response_.CalculateSize(_repeated_response_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GrpcResponses other) {
      if (other == null) {
        return;
      }
      response_.Add(other.response_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            response_.AddEntriesFrom(input, _repeated_response_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GrpcResponse : pb::IMessage<GrpcResponse> {
    private static readonly pb::MessageParser<GrpcResponse> _parser = new pb::MessageParser<GrpcResponse>(() => new GrpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GrpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.Contract.GrpcReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcResponse(GrpcResponse other) : this() {
      collector_ = other.collector_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcResponse Clone() {
      return new GrpcResponse(this);
    }

    /// <summary>Field number for the "collector" field.</summary>
    public const int CollectorFieldNumber = 1;
    private int collector_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Collector {
      get { return collector_; }
      set {
        collector_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GrpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GrpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Collector != other.Collector) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Collector != 0) hash ^= Collector.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Collector != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Collector);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Collector != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Collector);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GrpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.Collector != 0) {
        Collector = other.Collector;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Collector = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
