// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LuckQueries.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;

using grpc = global::Grpc.Core;

namespace Queries.Contract.protos {
  public static partial class GrpcQueryService
  {
    static readonly string __ServiceName = "LuckProto.GrpcQueryService";

    static readonly grpc::Marshaller<global::Queries.Contract.protos.LuckRequest> __Marshaller_LuckRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Queries.Contract.protos.LuckRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Queries.Contract.protos.LuckResponse> __Marshaller_LuckResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Queries.Contract.protos.LuckResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Queries.Contract.protos.LuckRequest, global::Queries.Contract.protos.LuckResponse> __Method_GetLuck = new grpc::Method<global::Queries.Contract.protos.LuckRequest, global::Queries.Contract.protos.LuckResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLuck",
        __Marshaller_LuckRequest,
        __Marshaller_LuckResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Queries.Contract.protos.LuckQueriesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GrpcQueryService</summary>
    public abstract partial class GrpcQueryServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Queries.Contract.protos.LuckResponse> GetLuck(global::Queries.Contract.protos.LuckRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GrpcQueryService</summary>
    public partial class GrpcQueryServiceClient : grpc::ClientBase<GrpcQueryServiceClient>
    {
      /// <summary>Creates a new client for GrpcQueryService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GrpcQueryServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GrpcQueryService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GrpcQueryServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GrpcQueryServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GrpcQueryServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Queries.Contract.protos.LuckResponse GetLuck(global::Queries.Contract.protos.LuckRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetLuck(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Queries.Contract.protos.LuckResponse GetLuck(global::Queries.Contract.protos.LuckRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetLuck, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Queries.Contract.protos.LuckResponse> GetLuckAsync(global::Queries.Contract.protos.LuckRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetLuckAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Queries.Contract.protos.LuckResponse> GetLuckAsync(global::Queries.Contract.protos.LuckRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetLuck, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GrpcQueryServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GrpcQueryServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GrpcQueryServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetLuck, serviceImpl.GetLuck).Build();
    }

  }
}
#endregion
